---

name: build-and-push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Fetch latest commit-ID from taskd repository
        run: |
          echo "TASKD_COMMIT=$(git ls-remote 'https://github.com/GothenburgBitFactory/taskserver.git' refs/heads/1.2.0 | cut -b -7)" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: TASKD_COMMIT=${{ env.TASKD_COMMIT }}
          push: true
          tags: philipgatzka/docker-taskd:latest,philipgatzka/docker-taskd:${{ env.TASKD_COMMIT }}
          cache-from: type=registry,ref=philipgatzka/docker-taskd:buildcache
          cache-to: type=registry,ref=philipgatzka/docker-taskd:buildcache,mode=max
